// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1qvg0Sa71HYRIxbFDonKg7gw207lbxy0',
    appId: '1:383342764470:web:b7b40f26399ea943096117',
    messagingSenderId: '383342764470',
    projectId: 'docshield-86949',
    authDomain: 'docshield-86949.firebaseapp.com',
    storageBucket: 'docshield-86949.firebasestorage.app',
    measurementId: 'G-CKTDHT2LLR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmSn5nosYUSFdCHHbp6IYIO91byYZaa0A',
    appId: '1:383342764470:android:a0e4b8d7a7543a0f096117',
    messagingSenderId: '383342764470',
    projectId: 'docshield-86949',
    storageBucket: 'docshield-86949.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCKXjGL-yc4pTqX_ptJrg1vf-Wz4leSQU',
    appId: '1:383342764470:ios:1a3e51bff1126321096117',
    messagingSenderId: '383342764470',
    projectId: 'docshield-86949',
    storageBucket: 'docshield-86949.firebasestorage.app',
    iosBundleId: 'com.example.docshield',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCKXjGL-yc4pTqX_ptJrg1vf-Wz4leSQU',
    appId: '1:383342764470:ios:1a3e51bff1126321096117',
    messagingSenderId: '383342764470',
    projectId: 'docshield-86949',
    storageBucket: 'docshield-86949.firebasestorage.app',
    iosBundleId: 'com.example.docshield',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1qvg0Sa71HYRIxbFDonKg7gw207lbxy0',
    appId: '1:383342764470:web:7d4449c7fe2b4be2096117',
    messagingSenderId: '383342764470',
    projectId: 'docshield-86949',
    authDomain: 'docshield-86949.firebaseapp.com',
    storageBucket: 'docshield-86949.firebasestorage.app',
    measurementId: 'G-HKQZS2VC26',
  );
}
